# Generated by Django 4.0.4 on 2022-04-20 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkb', '0004_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
    ]
