# Generated by Django 4.0.4 on 2022-04-21 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkb', '0006_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
