# Generated by Django 4.0.4 on 2022-04-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkb', '0007_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_subj', models.CharField(max_length=10)),
                ('task_content', models.CharField(max_length=200)),
            ],
        ),
    ]
